# Generated by Django 2.2.18 on 2021-03-22 13:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0006_create_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 13, 13, 25, 167568, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
