# Generated by Django 2.2.18 on 2021-03-25 16:44

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0007_auto_20210322_1313"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 3, 27, 16, 44, 7, 385398, tzinfo=utc), verbose_name="актуальность ключа"
            ),
        ),
    ]
